language: node_js
sudo: false

node_js:
- 8
- 7

cache:
  yarn: true
  directories:
  - node_modules

script:
- node --version
- npm run lint
- npm run build
- npm package:linux
- npm run clean
- npm run build:web
- npm run test

