language: node_js
sudo: false

node_js:
- "8"

cache:
  yarn: false
  directories:
  - node_modules

script:
- npm run lint
- npm run test
- npm run build
- npm run build:web
- npm run clean

after_success:
- npm run package:linux
